name: havass_coaching_flutter
description: Havass Coaching App Project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.3.0
  cloud_firestore: ^2.3.0
  firebase_storage: ^9.0.0
  firebase_auth: ^2.0.0
  provider: ^5.0.0
  google_sign_in: ^5.0.4
  flutter_bloc: ^7.0.1
  shared_preferences: ^2.0.6
  path_provider: ^2.0.2
  flutter_localizations: 
    sdk: flutter
  overlay_support: ^1.2.1
  splash_screen_view: ^3.0.0
  stripe_payment: ^1.1.3
  http: ^0.13.3
  credit_card_input_form: ^2.3.0
  calendar_timeline: ^0.7.1
  bubble_bottom_bar: ^1.2.0
  flutter_html: ^2.1.0
  advance_pdf_viewer: ^2.0.0
  flutter_html_to_pdf: ^0.6.1
  flutter_windowmanager: ^0.1.0
  scratcher: ^2.1.0
  badges: ^2.0.1
  url_launcher: ^6.0.8
  font_awesome_flutter: ^9.1.0
  permission_handler: ^8.1.2
  firebase_messaging: ^10.0.3
  flutter_downloader:
    git:
      url: https://github.com/fluttercommunity/flutter_downloader.git
      ref: embedding-v2
  assets_audio_player: ^3.0.3+3
  ntp: ^2.0.0
  uuid: ^3.0.4
  wc_flutter_share: ^0.4.0
  cached_network_image: ^3.0.0
  introduction_screen: ^2.1.0
  flutter_quill: ^1.6.1
  pdf: ^3.4.2
  open_file: ^3.2.1



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - langs/
    - images/
    - images/mandala_images/
    - images/home/
    - images/audio/
    - images/pdf/
  #   - images/a_dot_ham.jpeg


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
